# Generated by Django 3.2 on 2023-04-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCheckoutTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.CharField(max_length=500)),
                ('execution_time', models.DateTimeField()),
                ('executed', models.BooleanField(default=False)),
            ],
        ),
    ]
