# Generated by Django 3.2 on 2023-04-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderPro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordercheckouttasks',
            old_name='OrderID',
            new_name='checkoutID',
        ),
    ]
